[build]
command = "echo 'no op'"
publish = "example"

[build.environment]
NODE_VERSION = "15"

[[plugins]]
package = "./src/index.js"

[plugins.inputs.thresholds]
performance = 0.9

[[plugins.inputs.audits]]
path = "route1"
[[plugins.inputs.audits]]
path = "route2"
[[plugins.inputs.audits]]
path = ""
